apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-code-generator
  name: api-code-generator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: api-code-generator
status:
  loadBalancer: {}
