apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-qr-code-generator-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: frontend.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-code-generator-service
                port:
                  number: 80
