--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-code-generator-configmap
data:
 
  bucket_name: "<replace with your bucket name>"
  frontend_origin: "frontend-code-generator-service.default.svc.cluster.local" 
  app_backend_url: "http://api-code-generator.default.svc.cluster.local:8000"
 
